name: multi_mode_animated_snack
description: "A customizable and multi-mode animated snackbar for Flutter."
version: 0.1.1
homepage: https://github.com/GingerMustache/multi_mode_snack_bar
repository: https://github.com/GingerMustache/multi_mode_snack_bar
issue_tracker: https://github.com/GingerMustache/multi_mode_snack_bar/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2  

dev_dependencies:

flutter:
  # no assets or fonts for now, clean

# Add Pub.dev metadata for points
topics:
  - snackbar
  - animation
  - flutter
  - widget
  - ui

# Optional, recommended
platforms:
  android:
  ios:
  web:
  linux:
  macos:
  windows:
